# Generated by Django 4.1.3 on 2022-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='students',
            field=models.ManyToManyField(to='mysite.student'),
        ),
    ]
