# Generated by Django 4.1.3 on 2022-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_journal_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
