# Generated by Django 4.1.3 on 2022-11-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_student_user_delete_post_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='student',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.topic')),
            ],
        ),
    ]
