# Generated by Django 4.1.3 on 2022-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_topic_mark_remove_topic_student_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='journal',
        ),
        migrations.AddField(
            model_name='student',
            name='journal',
            field=models.ManyToManyField(null=True, to='mysite.journal'),
        ),
    ]
